import Link from "next/link";
import React, { useEffect } from "react";
import Head from "next/head";

const Posts = () => {
  return (
    <div className="center items-start child:mb-4">
      <Head>
        <title>Categories</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="hover:underline">
        <Link href="/posts/general-discussion">General Discussion</Link>
      </div>
      <div className="hover:underline">
        <Link href="/posts/lore">Lore</Link>
      </div>
      <div className="hover:underline">
        <Link href="/posts/off-topic">Off-Topic</Link>
      </div>
      <div className="hover:underline">
        <Link href="/posts/news">News</Link>
      </div>
    </div>
  );
};

export default Posts;
