import Head from "next/head";

export default function Home() {
  return (
    <div className="dark:bg-bgDark bg-bgLight dark:text-textDark text-textLight">
      <Head>
        <title>Forum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>forum app</h2>
    </div>
  );
}
