import Head from "next/head";
import cookie from "cookie";
import axios from "axios";

export default function Home() {
  return (
    <div className="bg-bgLight text-textLight dark:bg-bgDark dark:text-textDark">
      <Head>
        <title>Forum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>forum app</h2>
    </div>
  );
}
