import Head from "next/head";
import React from "react";
import createToken from "../utils/createToken";
import { setCookie } from "nookies";

const Login = () => {
  const handleLogin = async (event: React.SyntheticEvent) => {
    event.preventDefault();

    const email = (event?.target as any).email.value;
    const password = (event?.target as any).password.value;

    const data = {
      email,
      password,
    };

    const resp = await fetch("/api/login", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    });

    const userData = await resp.json();

    const token = createToken(userData);

    setCookie(null, "tk", token, {
      maxAge: 30 * 24 * 60 * 60, //1 week
      path: "/",
    });
  };

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={handleLogin}>
        <div>
          <input type="text" name="email" placeholder="email" />
        </div>
        <div>
          <input type="text" name="password" placeholder="password" />
        </div>

        <button>Submit</button>
      </form>
    </div>
  );
};

export default Login;
