import Head from "next/head";
import React, { useState } from "react";
import createToken from "../utils/createToken";
import { setCookie } from "nookies";
import { useRouter } from "next/router";

const Login = () => {
  const [error, setError] = useState(false);

  const router = useRouter();

  const handleLogin = async (event: React.SyntheticEvent) => {
    event.preventDefault();

    const email = (event?.target as any).email.value;
    const password = (event?.target as any).password.value;

    if (email === "" || password === "") {
      setError(true);
      return;
    }

    const data = {
      email,
      password,
    };

    const resp = await fetch("/api/login", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    });

    const userData = await resp.json();

    if (userData.ok) {
      router.push("/");
    } else {
      setError(true);
    }
  };

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {error && <h2 className="text-error">Email or Password Wrong</h2>}
      <form onSubmit={handleLogin}>
        <div>
          <input type="text" name="email" placeholder="email" />
        </div>
        <div>
          <input type="text" name="password" placeholder="password" />
        </div>

        <button>Submit</button>
      </form>
    </div>
  );
};

export default Login;
