import Head from "next/head";
import React, { useState } from "react";
import createToken from "../utils/createToken";
import { setCookie } from "nookies";
import { useRouter } from "next/router";

const Login = () => {
  const [error, setError] = useState(false);
  const [showPass, setShowPass] = useState(false);

  const router = useRouter();

  const handleLogin = async (event: React.SyntheticEvent) => {
    event.preventDefault();

    const email = (event?.target as any).email.value;
    const password = (event?.target as any).password.value;

    if (email === "" || password === "") {
      setError(true);
      return;
    }

    const data = {
      email,
      password,
    };

    const resp = await fetch("/api/login", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    });

    const userData = await resp.json();

    if (userData.ok) {
      router.push("/");
    } else {
      setError(true);
    }
  };

  return (
    <div className="center">
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2 className="title mb-8">LOGIN</h2>
      {error && <h2 className="text-error">Email or Password Wrong</h2>}
      <form onSubmit={handleLogin}>
        <div>
          <input
            className="inputStyle mb-2 dark:text-textLight"
            type="text"
            name="email"
            placeholder="email"
          />
        </div>
        <div>
          <div>
            <input
              className="inputStyle dark:text-textLight"
              type={showPass ? "text" : "password"}
              name="password"
              placeholder="password"
            />
          </div>
          <div className="mt-2 flex items-center justify-center">
            <input
              onChange={() => setShowPass((prev) => !prev)}
              className="mr-2"
              type="checkbox"
              id="horns"
              name="horns"
            />
            <label htmlFor="horns">Show password</label>
          </div>
        </div>

        <button className="btn mt-6">Submit</button>
      </form>
    </div>
  );
};

export default Login;
