import Head from "next/head";
import React from "react";
import { parseCookies } from "nookies";

const Register = () => {
  const handleSubmit = async (event: React.SyntheticEvent) => {
    event.preventDefault();

    const name = (event?.target as any).nome.value;
    const email = (event?.target as any).email.value;
    const password = (event?.target as any).password.value;

    const data = {
      name,
      email,
      password,
    };

    const resp = await fetch("/api/register", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    });

    const data2 = await resp.json();

    console.log(data2);
  };

  const cookies = parseCookies();

  return (
    <div>
      <Head>
        <title>Forum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form onSubmit={handleSubmit}>
        <div>
          <input type="text" name="nome" placeholder="name" />
        </div>
        <div>
          <input type="text" name="email" placeholder="email" />
        </div>
        <div>
          <input type="text" name="password" placeholder="password" />
        </div>

        <button>Submit</button>
      </form>
    </div>
  );
};

export default Register;
