import Head from "next/head";
import { useState } from "react";

const Register = () => {
  const [error, setError] = useState(false);
  const [showPass, setShowPass] = useState(false);

  const handleSubmit = async (event: React.SyntheticEvent) => {
    event.preventDefault();

    const name = (event?.target as any).nome.value;
    const email = (event?.target as any).email.value;
    const password = (event?.target as any).password.value;

    if (name === "" || email === "" || password === "") {
      setError(true);
      return;
    }

    const data = {
      name,
      email,
      password,
    };

    const resp = await fetch("http://localhost:5000/register", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    });

    const data2 = await resp.json();

    console.log(data2);
  };

  // const cookies = parseCookies();

  return (
    <div className="center text-textLight">
      <Head>
        <title>Forum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className="title mb-8">Register</h2>
      {error && <h2 className="text-error">Please enter all fields</h2>}
      <form onSubmit={handleSubmit}>
        <div>
          <input
            className="inputStyle mb-2"
            type="text"
            name="nome"
            placeholder="name"
          />
        </div>
        <div>
          <input
            className="inputStyle mb-2"
            type="text"
            name="email"
            placeholder="email"
          />
        </div>
        <div>
          <div>
            <input
              className="inputStyle dark:text-textLight"
              type={showPass ? "text" : "password"}
              name="password"
              placeholder="password"
            />
          </div>
          <div className="mt-2 flex items-center justify-center">
            <input
              onChange={() => setShowPass((prev) => !prev)}
              className="mr-2"
              type="checkbox"
              id="showPas"
              name="showPas"
            />
            <label className="dark:text-textDark" htmlFor="showPas">
              Show password
            </label>
          </div>
        </div>

        <button className="btn mt-6 dark:text-textDark">Submit</button>
      </form>
    </div>
  );
};

export default Register;
