import Head from "next/head";
import { useState } from "react";
import { parseCookies } from "nookies";

const Register = () => {
  const [error, setError] = useState(false);

  const handleSubmit = async (event: React.SyntheticEvent) => {
    event.preventDefault();

    const name = (event?.target as any).nome.value;
    const email = (event?.target as any).email.value;
    const password = (event?.target as any).password.value;

    if (name === "" || email === "" || password === "") {
      setError(true);
      return;
    }

    const data = {
      name,
      email,
      password,
    };

    const resp = await fetch("/api/register", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    });

    const data2 = await resp.json();

    console.log(data2);
  };

  const cookies = parseCookies();

  return (
    <div className="center">
      <Head>
        <title>Forum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className="title mb-8">Register</h2>
      {error && <h2 className="text-error">Please enter all fields</h2>}
      <form onSubmit={handleSubmit}>
        <div>
          <input
            className="inputStyle mb-2"
            type="text"
            name="nome"
            placeholder="name"
          />
        </div>
        <div>
          <input
            className="inputStyle mb-2"
            type="text"
            name="email"
            placeholder="email"
          />
        </div>
        <div>
          <input
            className="inputStyle mb-6"
            type="text"
            name="password"
            placeholder="password"
          />
        </div>

        <button className="btn">Submit</button>
      </form>
    </div>
  );
};

export default Register;
